---

- name: Create the directory used to store binaries
  file: path={{ bin_dir }} state=directory

- name: Create Ansible temp directory
  file: path={{ ansible_temp_dir }} state=directory

- name: Determine if has rpm
  stat: path=/usr/bin/rpm
  register: rpm_check
  changed_when: false
  always_run: yes

- name: Set the has_rpm fact
  set_fact:
    has_rpm: true
  when: rpm_check.stat.exists


- include: rpm.yml
  when: has_rpm
