---


- name: Retrieve systemd files for github-release kube_source_type type
  include: retrieve-systemd-files.yml
  
- name: Force kube_source_type to github
  set_fact:
    kube_source_type: "github-release"

- include: download_bins.yml
  when: kube_source_type == "github-release"
  tags:
    - binary-update

- include: etcd-certs.yml
  when: apiserver_etcd_use_certs
