---

- name: Force kube_source_type to github
  set_fact:
    kube_source_type: "github-release"

- name: Generic | Install kubernetes master
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: kubernetes-master
    state: latest
  notify:
    - restart daemons

- include: localBuildInstall.yml
  when: kube_source_type == "localBuild"
  tags:
    - binary-update

- include: download_bins.yml
  when: kube_source_type == "github-release"
  tags:
    - binary-update

- include: install_rpms.yml
  when: kube_source_type == "distribution-rpm"
  tags:
    - binary-update

- include: etcd-certs.yml
  when: apiserver_etcd_use_certs
