---

- name: Install kube master
  include: install.yml
  tags: install

- name: Configure apiserver
  include: apiserver-configure.yml
  tags: configure

- name: Copy the certificates from the first master to the other masters
  include: cert-copy.yml

- name: Start apiserver
  include: apiserver-start.yml

- name: Collect master tokens
  include: collect-tokens.yml
  tags: configure

- name: Configure controller-manager
  include: controller-manager-configure.yml
  tags: configure

- name: Start controller-manager
  include: controller-manager-start.yml

- name: Configure scheduler
  include: scheduler-configure.yml
  tags: configure

- name: Start scheduler
  include: scheduler-start.yml

- name: Configure kubectl
  include: kubectl-configure.yml
  tags: configure

- name: Update firewalld to open apiserver port
  include: firewalld.yml
  when: has_firewalld
  tags: configure

- name: Update iptables to open apiserver port
  include: iptables.yml
  when: not has_firewalld and has_iptables
  tags: configure

- name: Call restart services
  include: restart-services.yml
