---


- name: Retrieve systemd files for github-release kube_source_type type
  include: retrieve-systemd-files.yml
  when: kube_source_type == "github-release" or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int == 16)

- name: Install conntrack (kube-proxy's runtime dependency)
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: conntrack
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Force kube_source_type to github
  set_fact:
    kube_source_type: "github-release"

- include: download_bins.yml
  when: kube_source_type == "github-release"
  tags:
    - binary-update
