---
- name: Disable swap
  include: swapoff.yml
  tags: configure
  when: disable_swap

- name: Install kube node
  include: install.yml
  tags: install

- name: Collect tokens for kubelet and proxy
  include: collect-tokens.yml
  tags: configure

- name: Configure kubelet
  include: kubelet-configure.yml
  tags: configure

- name: Start kubelet
  include: kubelet-start.yml

- name: Configure proxy
  include: proxy-configure.yml
  tags: configure

- name: Start proxy
  include: proxy-start.yml
  when: networking != "opencontrail"



- include: firewalld.yml
  when: has_firewalld
  tags: configure

- include: iptables.yml
  when: not has_firewalld and has_iptables
  tags: configure

- name: Call restart kubelet
  include: kubelet-restart.yml
  when: kubelet_modified == true and kubelet_started.changed == false
  tags: restart

- name: Call restart proxy
  include: proxy-restart.yml
  when: proxy_modified == true and proxy_started.changed == false
  tags: restart
