---
- name: Create etcd config directory
  file: path={{ etcd_conf_dir }} state=directory

- include: etcd-configure.yml

- include: firewalld-configure.yml
  when: has_firewalld

- include: iptables-configure.yml
  when: not has_firewalld and has_iptables
